package com.knd.duantotnghiep.testsocket.ui.chat_message

enum class ViewTypeChatMessage {
    TEXT_SENT,
    TEXT_RECEIVED,

    VIDEO_SENT,
    VIDEO_RECEIVED,

    IMAGE_SENT,
    IMAGE_RECEIVED,

    FILE_SENT,
    FILE_RECEIVED,

    RECORD_SENT,
    RECORD_RECEIVED,

    VIDEO_CALL_SENT,
    VIDEO_CALL_RECEIVED,

    VOICE_CALL_SENT,
    VOICE_CALL_RECEIVED,

    TEXT_REPLY_TEXT_FILE_RECORD_SENT,
    TEXT_REPLY_TEXT_FILE_RECORD_RECEIVED,

    FILE_REPLY_TEXT_FILE_RECORD_SENT,
    FILE_REPLY_TEXT_FILE_RECORD_RECEIVED,

    IMAGE_REPLY_TEXT_FILE_RECORD_SENT,
    IMAGE_REPLY_TEXT_FILE_RECORD_RECEIVED,

    VIDEO_REPLY_TEXT_FILE_RECORD_SENT,
    VIDEO_REPLY_TEXT_FILE_RECORD_RECEIVED,

    RECORD_REPLY_TEXT_FILE_RECORD_SENT,
    RECORD_REPLY_TEXT_FILE_RECORD_RECEIVED,

    TEXT_REPLY_IMAGE_VIDEO_SENT,
    TEXT_REPLY_IMAGE_VIDEO_RECEIVED,

    FILE_REPLY_IMAGE_VIDEO_SENT,
    FILE_REPLY_IMAGE_VIDEO_RECEIVED,

    IMAGE_REPLY_IMAGE_VIDEO_SENT,
    IMAGE_REPLY_IMAGE_VIDEO_RECEIVED,

    VIDEO_REPLY_IMAGE_VIDEO_SENT,
    VIDEO_REPLY_IMAGE_VIDEO_RECEIVED,

    RECORD_REPLY_IMAGE_VIDEO_SENT,
    RECORD_REPLY_IMAGE_VIDEO_RECEIVED;
}
